<#
.SYNOPSIS
    Generates CSS Custom Properties and Tailwind theme extensions for design systems.
.DESCRIPTION
    Compiles token definitions into CSS variables and Tailwind config fragments.
.PARAMETER System
    Target design system name (e.g. material3, apple, fluent, carbon, ant, polaris, atlassian, shadcn). Default: material3.
.PARAMETER OutputFile
    Target path for generated CSS custom variables stylesheet. Default: .agents/skills/design-systems-pro/examples/minimal-tokens/theme.css
#>
param (
    [string]$System = "material3",
    [string]$OutputFile = ".agents/skills/design-systems-pro/examples/minimal-tokens/theme.css"
)

$ErrorActionPreference = "Stop"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "   DESIGN-SYSTEMS-PRO: Token Generator                   " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "Target Design System: $System" -ForegroundColor Yellow

$Tokens = @{
    "material3" = @{
        "--sys-color-primary" = "#6750A4";
        "--sys-color-on-primary" = "#FFFFFF";
        "--sys-color-primary-container" = "#EADDFF";
        "--sys-color-on-primary-container" = "#21005D";
        "--sys-color-surface" = "#FEF7FF";
        "--sys-color-on-surface" = "#1D1B20";
        "--sys-color-outline" = "#79747E";
        "--sys-radius-small" = "8px";
        "--sys-radius-medium" = "12px";
        "--sys-radius-large" = "16px";
        "--sys-radius-pill" = "9999px";
        "--sys-elevation-1" = "0px 1px 3px 1px rgba(0, 0, 0, 0.15)";
        "--sys-elevation-2" = "0px 2px 6px 2px rgba(0, 0, 0, 0.15)";
    };
    "apple" = @{
        "--sys-color-primary" = "#007AFF";
        "--sys-color-on-primary" = "#FFFFFF";
        "--sys-color-surface" = "rgba(255, 255, 255, 0.75)";
        "--sys-color-on-surface" = "#000000";
        "--sys-color-outline" = "rgba(60, 60, 67, 0.29)";
        "--sys-radius-small" = "6px";
        "--sys-radius-medium" = "10px";
        "--sys-radius-large" = "14px";
        "--sys-radius-pill" = "9999px";
        "--sys-backdrop-blur" = "blur(20px) saturate(180%)";
    };
    "fluent" = @{
        "--sys-color-primary" = "#0078D4";
        "--sys-color-on-primary" = "#FFFFFF";
        "--sys-color-surface" = "#FFFFFF";
        "--sys-color-on-surface" = "#242424";
        "--sys-color-outline" = "#D1D1D1";
        "--sys-radius-small" = "4px";
        "--sys-radius-medium" = "8px";
        "--sys-radius-large" = "12px";
        "--sys-radius-pill" = "9999px";
    };
    "shadcn" = @{
        "--sys-color-primary" = "#09090B";
        "--sys-color-on-primary" = "#FAFAFA";
        "--sys-color-surface" = "#FFFFFF";
        "--sys-color-on-surface" = "#09090B";
        "--sys-color-outline" = "#E4E4E7";
        "--sys-radius-small" = "calc(var(--radius) - 4px)";
        "--sys-radius-medium" = "var(--radius)";
        "--sys-radius-large" = "calc(var(--radius) + 4px)";
        "--sys-radius-pill" = "9999px";
    }
}

$SelectedTokens = $Tokens[$System.ToLower()]
if (-not $SelectedTokens) {
    Write-Host "[FALLBACK] System '$System' using material3 token base" -ForegroundColor Yellow
    $SelectedTokens = $Tokens["material3"]
}

$CssContent = "/* Generated by design-systems-pro ($System) */`n:root {`n"
foreach ($Key in $SelectedTokens.Keys) {
    $Val = $SelectedTokens[$Key]
    $CssContent += "  ${Key}: ${Val};`n"
}
$CssContent += "}`n"

$OutputDir = Split-Path -Parent $OutputFile
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

Set-Content -Path $OutputFile -Value $CssContent -Encoding UTF8
Write-Host "SUCCESS: Generated $OutputFile ($($SelectedTokens.Count) tokens compiled)" -ForegroundColor Green
