<#
.SYNOPSIS
    Scaffolds a new skill folder for the GeoSource Antigravity IDE workspace.

.DESCRIPTION
    Reads resources/skill_template.md and creates a complete skill directory structure
    under .agents/skills/<skill-name>/. Replaces all template placeholders with values
    provided as parameters.

.PARAMETER SkillName
    The slug name for the skill (lowercase, hyphenated). Example: "tauri-builder"

.PARAMETER Description
    One-paragraph description of what the skill does.

.PARAMETER Triggers
    Comma-separated list of trigger phrases. Example: "build app,tauri build,create release"

.PARAMETER Domain
    Short domain label. Example: "Tauri Build Automation"

.EXAMPLE
    .\generate_skill.ps1 -SkillName "tauri-builder" -Description "Builds the GeoSource Tauri app" -Triggers "build app,tauri build" -Domain "Tauri Automation"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$SkillName,

    [Parameter(Mandatory=$true)]
    [string]$Description,

    [Parameter(Mandatory=$true)]
    [string]$Triggers,

    [Parameter(Mandatory=$true)]
    [string]$Domain
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Resolve paths ──────────────────────────────────────────────────────────────
$scriptDir     = $PSScriptRoot
$skillRoot     = Split-Path $scriptDir -Parent
$workspaceRoot = Resolve-Path (Join-Path $skillRoot "..\..\")
$templatePath  = Join-Path $skillRoot "resources\skill_template.md"
$targetDir     = Join-Path $workspaceRoot ".agents\skills\$SkillName"

Write-Host ""
Write-Host "=== Skill Designer Pro — Generate Skill ===" -ForegroundColor Cyan
Write-Host "Skill Name : $SkillName"
Write-Host "Domain     : $Domain"
Write-Host "Output Dir : $targetDir"
Write-Host ""

# ── Guard: already exists? ──────────────────────────────────────────────────────
if (Test-Path $targetDir) {
    Write-Warning "Directory already exists: $targetDir"
    $overwrite = Read-Host "Overwrite? (y/N)"
    if ($overwrite -notmatch '^[yY]$') {
        Write-Host "Aborted." -ForegroundColor Yellow
        exit 0
    }
}

# ── Read template ───────────────────────────────────────────────────────────────
if (-not (Test-Path $templatePath)) {
    Write-Error "Template not found: $templatePath"
    exit 1
}
$template = Get-Content $templatePath -Raw

# ── Build trigger YAML block ────────────────────────────────────────────────────
$triggerList = $Triggers -split ',' | ForEach-Object { "  - `"$($_.Trim())`"" }
$triggerYaml = $triggerList -join "`n"

# ── Replace placeholders ────────────────────────────────────────────────────────
$skillContent = $template `
    -replace '\{\{SKILL_NAME\}\}',   $SkillName `
    -replace '\{\{DESCRIPTION\}\}',  $Description `
    -replace '\{\{DOMAIN\}\}',       $Domain `
    -replace '\{\{TRIGGERS\}\}',     $triggerYaml `
    -replace '\{\{DATE\}\}',         (Get-Date -Format "yyyy-MM-dd")

# ── Create directory structure ──────────────────────────────────────────────────
$subDirs = @("scripts", "examples", "resources", "references", "tests", "tests\expected_outputs")
New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
foreach ($sub in $subDirs) {
    New-Item -ItemType Directory -Force -Path (Join-Path $targetDir $sub) | Out-Null
}

# ── Write SKILL.md ─────────────────────────────────────────────────────────────
$skillMdPath = Join-Path $targetDir "SKILL.md"
Set-Content -Path $skillMdPath -Value $skillContent -Encoding UTF8

# ── Write README.md stub ───────────────────────────────────────────────────────
$readmeContent = @"
# $Domain

Generated by skill-designer-pro on $(Get-Date -Format "yyyy-MM-dd").

## Description
$Description

## Trigger Phrases
$(($Triggers -split ',') -join "`n- " | ForEach-Object { "- $_" })

## Files
- ``SKILL.md`` — Core agent instructions
- ``scripts/`` — Helper automation scripts
- ``examples/`` — Reference implementations
- ``resources/`` — Templates and assets
- ``references/`` — Supplemental documentation
- ``tests/`` — Validation scripts
"@
Set-Content -Path (Join-Path $targetDir "README.md") -Value $readmeContent -Encoding UTF8

# ── Write script stubs ─────────────────────────────────────────────────────────
$primaryScript = @"
<#
.SYNOPSIS
    Primary automation script for the $Domain skill.
    Generated by skill-designer-pro.
#>
[CmdletBinding()]
param()
Set-StrictMode -Version Latest
`$ErrorActionPreference = "Stop"

Write-Host "[$SkillName] Running primary script..." -ForegroundColor Cyan
# TODO: Implement skill-specific automation here
"@
Set-Content -Path (Join-Path $targetDir "scripts\main.ps1") -Value $primaryScript -Encoding UTF8

# ── Write examples README ─────────────────────────────────────────────────────
$examplesReadme = @"
# Examples — $Domain

This directory contains reference implementations for the $SkillName skill.

## How to Use
1. Browse the example sub-folders
2. Read the inline comments for context
3. Adapt patterns to your use case
"@
Set-Content -Path (Join-Path $targetDir "examples\README.md") -Value $examplesReadme -Encoding UTF8

# ── Write placeholder resource ────────────────────────────────────────────────
$resourceStub = "# Resources — $Domain`n`nPlace assets, config files, and templates here."
Set-Content -Path (Join-Path $targetDir "resources\notes.md") -Value $resourceStub -Encoding UTF8

# ── Write placeholder reference ──────────────────────────────────────────────
$refStub = "# Reference Guide — $Domain`n`nAdd supplemental documentation here for the agent to read on demand."
Set-Content -Path (Join-Path $targetDir "references\guide.md") -Value $refStub -Encoding UTF8

# ── Write test stub ──────────────────────────────────────────────────────────
$testScript = @"
<#
.SYNOPSIS
    Validation tests for the $SkillName skill.
    Generated by skill-designer-pro.
#>
Set-StrictMode -Version Latest
`$ErrorActionPreference = "Stop"
`$passed = 0; `$failed = 0

function Assert-True {
    param([string]`$label, [bool]`$condition)
    if (`$condition) { Write-Host "[PASS] `$label" -ForegroundColor Green; `$script:passed++ }
    else             { Write-Host "[FAIL] `$label" -ForegroundColor Red;   `$script:failed++ }
}

`$skillDir = Resolve-Path (Join-Path `$PSScriptRoot "..")
Assert-True "SKILL.md exists"      (Test-Path "`$skillDir\SKILL.md")
Assert-True "README.md exists"     (Test-Path "`$skillDir\README.md")
Assert-True "scripts/ exists"      (Test-Path "`$skillDir\scripts")
Assert-True "examples/ exists"     (Test-Path "`$skillDir\examples")
Assert-True "resources/ exists"    (Test-Path "`$skillDir\resources")
Assert-True "references/ exists"   (Test-Path "`$skillDir\references")

Write-Host ""
Write-Host "Results: `$passed passed, `$failed failed"
if (`$failed -gt 0) { exit 1 } else { exit 0 }
"@
Set-Content -Path (Join-Path $targetDir "tests\test_validation.ps1") -Value $testScript -Encoding UTF8

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host "Skill generated successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Created files:" -ForegroundColor Cyan
Get-ChildItem -Path $targetDir -Recurse -File | ForEach-Object {
    Write-Host "  $($_.FullName.Replace($targetDir, '.'))"
}
Write-Host ""
Write-Host "Next: Run .\validate_skill.ps1 -SkillPath '$targetDir' to validate."
