/**
 * @file gen-ipc.js
 * @description Generator tool for Tauri IPC Rust handlers and TypeScript wrapper functions.
 */

const fs = require('fs');
const path = require('path');

function parseArgs() {
  const args = process.argv.slice(2);
  const result = { name: 'example_command', params: [] };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--name' && args[i + 1]) {
      result.name = args[i + 1];
      i++;
    } else if (args[i] === '--args' && args[i + 1]) {
      result.params = args[i + 1].split(',').map((p) => p.trim());
      i++;
    }
  }
  return result;
}

const config = parseArgs();
const pascalName = config.name.replace(/(^\w|_\w)/g, (m) => m.replace('_', '').toUpperCase());

console.log(`=== Tauri IPC Generator: ${config.name} ===\n`);

const rustParams = config.params.length > 0
  ? config.params.map((p) => `    ${p}`).join(',\n')
  : '';

const rustCode = `
/// Executable IPC Handler: ${config.name}
/// Auto-generated by .agents/scripts/gen-ipc.js
#[tauri::command]
pub async fn ${config.name}(
${rustParams}
) -> Result<String, String> {
    // TODO: Implement Rust logic for ${config.name}
    Ok(format!("Successfully executed ${config.name}"))
}
`;

const tsParams = config.params.length > 0
  ? config.params.map((p) => `  ${p.replace(/\s*:\s*/, ': ')}`).join(',\n')
  : '';

const tsInvokeArgs = config.params.length > 0
  ? config.params.map((p) => `    ${p.split(':')[0].trim()}`).join(',\n')
  : '';

const tsCode = `
import { invoke } from '@tauri-apps/api/core';

/**
 * TypeScript Invoke Wrapper: ${config.name}
 * Auto-generated by .agents/scripts/gen-ipc.js
 */
export async function invoke${pascalName}(
${tsParams}
): Promise<string> {
  return await invoke<string>('${config.name}', {
${tsInvokeArgs}
  });
}
`;

console.log('Generated Rust Command Spec:');
console.log(rustCode);
console.log('Generated TypeScript Invoke Wrapper:');
console.log(tsCode);
console.log('✅ Generator template output complete. Add to your src-tauri and frontend API modules.');
