<#
.SYNOPSIS
    Generates a minimal stub (signatures only) from a source file.

.DESCRIPTION
    Extracts function/struct/impl/class signatures from source files without
    their bodies. Produces a compact stub suitable for injecting into AI context
    instead of the full file. Supports Rust (.rs), TypeScript (.ts, .svelte),
    and PowerShell (.ps1).

    Output is written to stdout and optionally saved to a .stub file.

.PARAMETER FilePath
    Path to the source file to stub.

.PARAMETER OutFile
    Optional path to write the stub file. If omitted, prints to stdout.

.EXAMPLE
    .\generate_stub.ps1 -FilePath "src-tauri/src/commands/geo.rs"
    .\generate_stub.ps1 -FilePath "src/lib/MapStore.ts" -OutFile "resources/stubs/MapStore.stub"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$FilePath,

    [string]$OutFile
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $FilePath)) {
    Write-Error "File not found: $FilePath"
    exit 1
}

$ext  = [System.IO.Path]::GetExtension($FilePath).ToLower()
$lines = Get-Content -LiteralPath $FilePath

$stub  = [System.Collections.Generic.List[string]]::new()
$stub.Add("// STUB: $FilePath")
$stub.Add("// Generated by generate_stub.ps1 - bodies omitted for token efficiency")
$stub.Add("")

$depth = 0

switch ($ext) {
    { $_ -in '.rs' } {
        foreach ($line in $lines) {
            $trimmed = $line.TrimStart()
            # Track brace depth
            $depth += ($line.ToCharArray() | Where-Object { $_ -eq '{' }).Count
            $depth -= ($line.ToCharArray() | Where-Object { $_ -eq '}' }).Count

            # Capture: pub fn, fn, struct, enum, impl, trait, mod, use, const, type at top level
            if ($depth -le 1 -and $trimmed -match '^(pub(\s+\w+)?\s+)?(fn|struct|enum|impl|trait|mod|use|const|type)\s') {
                $stub.Add($line.TrimEnd())
                if ($trimmed -match '\{') { $stub.Add("    // ... body omitted") }
            }
        }
    }
    { $_ -in '.ts', '.svelte' } {
        foreach ($line in $lines) {
            $trimmed = $line.TrimStart()
            $depth += ($line.ToCharArray() | Where-Object { $_ -eq '{' }).Count
            $depth -= ($line.ToCharArray() | Where-Object { $_ -eq '}' }).Count

            if ($depth -le 1 -and $trimmed -match '^(export\s+)?(function|class|interface|type|const|let|var|async function|enum)\s') {
                $stub.Add($line.TrimEnd())
                if ($trimmed -match '\{') { $stub.Add("    // ... body omitted") }
            }
        }
    }
    '.ps1' {
        foreach ($line in $lines) {
            $trimmed = $line.TrimStart()
            if ($trimmed -match '^(function|param\s*\()') {
                $stub.Add($line.TrimEnd())
            }
        }
    }
    default {
        # Generic: first 20 lines as stub header
        $stub.Add("// Unsupported extension '$ext' - showing first 20 lines as stub")
        $lines | Select-Object -First 20 | ForEach-Object { $stub.Add($_) }
    }
}

$stubText = $stub -join "`n"

if ($OutFile) {
    $stubText | Set-Content -LiteralPath $OutFile -Encoding UTF8
    Write-Host "Stub written to: $OutFile" -ForegroundColor Green
} else {
    Write-Output $stubText
}
